hwj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('messages/', include('chat.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register('requests', views.RequestsView)
router.register('profiles', views.ProfileView)

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('open_requests', views.open_requests, name='open_requests'),
    path('create_request', views.create_request, name='create_request'),
    path('view_past_requests', views.past_requests, name='past_requests'),
    path('profile', views.profile, name='profile'),
    path('inbox', views.inbox, name='inbox'),
    path('non_profits', views.non_profits, name='non_profits'),
    path('api/', include(router.urls)),
    path('support', views.support, name='support'),
    path('organization_register', views.organization_register, name='organization_register'),
]

chat/models.py
from django.db import models
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from user.models import Profile
import re
from django.contrib import admin


class ThreadManager(models.Manager):

    def by_user(self, user):

        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()

        return qs

    def get_or_new(self, user, other_username):  # get_or_create

        username = user.username

        if username == other_username:
            return None

        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)

        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()

        if qs.count() == 1:

            return qs.first(), False

        elif qs.count() > 1:

            return qs.order_by('timestamp').first(), False

        else:

            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)

            if user != user2:
                obj = self.model(first=user, second=user2)
                obj.save()
                return obj, True

            return None, False


class Thread(models.Model):

    first = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    def __str__(self):
        return f'Chat between {self.first} & {self.second}'

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True

        return False


CHAT_STATUS_CHOICES = [
    ('n', 'New'),
    ('c', 'Clean'),
    ('i', 'Inappropriate'),
]


class ChatMessage(models.Model):

    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=CHAT_STATUS_CHOICES, default='n')


def check_message(message):

    phone_number_regex = "\(\w{3}\)\w{3}-\w{4}"

    email_regex = "(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"

    if re.search(email_regex, message) or re.search(phone_number_regex, message):

        ret_value = 'i'
        return ret_value

    else:

        ret_value = 'c'
        return ret_value


def search_messages():

    query_all_messages = ThreadManager.ChatMessage.objects.all()

    phone_number_regex= "\(\w{3}\)\w{3}-\w{4}"

    email_regex = "(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"

    for message in query_all_messages:

        if re.search(email_regex, message) or re.search(phone_number_regex, message):

            return 'i'

        else:

            return 'c'

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms
from django.utils import timezone
from PIL import Image


# Create your models here.


REQUEST_TYPES = [
    ('Furniture Service', 'Furniture Service'),
    ('Interpreter Service', 'Interpreter Service'),
    ('Transportation Service', 'Transportation Service'),
    ('Clothing Service', 'Clothing Service'),
    ('Food Service', 'Food Service'),
]

FEEDBACK_TYPES = [
    ('None', 'None'),
    ('Positive', 'Positive'),
    ('Negative', 'Negative'),
]


class Requests(models.Model):

    status = models.CharField(max_length=50, default="Incomplete")
    description = models.CharField(max_length=500)
    type = models.CharField(choices=REQUEST_TYPES, max_length=50, default='Item Service')
    date_created = models.DateTimeField(auto_now_add=True)
    date_appointment = models.DateTimeField(null=True)
    date_completed = models.DateTimeField(null=True)
    appointment_confirmed = models.BooleanField(default=False)
    appointment_suggested = models.BooleanField(default=False)
    requester = models.ForeignKey(User, on_delete=models.CASCADE)
    accepter = models.CharField(max_length=150, null=True)
    accepter_is_verified = models.BooleanField(default=False)
    accepter_rated_positive = models.BooleanField(null=True)
    requester_rated_positive = models.BooleanField(null=True)
    reported = models.BooleanField(default=False)

    def __str__(self):
        return self.description


class RequestForm(ModelForm):

    class Meta:
        model = Requests
        fields = ['type', 'description']
        widgets = {'description': forms.Textarea}
        #description = forms.CharField(widget=forms.Textarea)


class AcceptRequestForm(ModelForm):

    class Meta:
        model = Requests
        fields = ['accepter']


class CancelRequestForm(ModelForm):

    class Meta:
        model = Requests
        fields = ['accepter']


class DeleteRequestForm(ModelForm):

    class Meta:
        model = Requests
        fields = ['requester']


class CloseRequestForm(ModelForm):

    class Meta:
        model = Requests
        fields = ['status']


class ScheduleAppointmentForm(forms.Form):

    class Meta:
        model = Requests
        fields = ['date_appointment']
        widgets = {
            'date_appointment': forms.DateTimeInput(attrs={'class': 'datetime-input', 'format': '%Y-%m-%d %H:%M'})
        }


class ConfirmAppointmentForm(ModelForm):

    class Meta:
        model = Requests
        fields = ['appointment_confirmed']


class DateForm(forms.Form):

    date = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M', ''], required=False)


SUPPORT_TICKET_STATUS = [
    ('p', 'Pending'),
    ('i', 'In-Progress'),
    ('c', 'Closed'),
]


class SupportTicket(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=500)
    body = models.CharField(max_length=500)
    date_created = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=SUPPORT_TICKET_STATUS, default='p')
    support_comment = models.CharField(max_length=200, default="This issue is still being processed. Check for updates later.")

    def __str__(self):

        return f'Subject: {self.subject}'


class SupportTicketForm(ModelForm):

    class Meta:
        model = SupportTicket
        fields = ['subject', 'body']
        widgets = {'body': forms.Textarea}


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="default_profile_image.jpg", upload_to="profile_pics")
    created_count = models.IntegerField(default=0)
    accepted_count = models.IntegerField(default=0)
    deleted_count = models.IntegerField(default=0)
    completed_count = models.IntegerField(default=0)
    canceled_count = models.IntegerField(default=0)
    other_user_messaged_count = models.IntegerField(default=0)
    reported_count = models.IntegerField(default=0)
    positive_feedback_count = models.IntegerField(default=0)
    negative_feedback_count = models.IntegerField(default=0)
    user_anniversary = models.DateField(auto_now_add=True)
    is_moderator = models.BooleanField(default=False)
    is_organization = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):

        super().save(*args, **kwargs)
        image = Image.open(self.image.path)

        if image.height > 500 or image.width > 500:

            output_size = (500, 500)
            image.thumbnail(output_size)
            image.save(self.image.path)

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserUpdateForm(forms.ModelForm):

    class Meta:

        model = User
        fields = ['username']


class ProfileUpdateForm(forms.ModelForm):

    class Meta:

        model = Profile
        fields = ['image']

user/templates/user/base.html
<!doctype html>

<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Help Without Judgment</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Chart JS -->
    <!--<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/v4-shims.css">

    <!-- Datepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous">
    <script type="text/javascript" src='http://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js'></script>
	<style>

		.container
		{
			font-family: 'Helvetica','Arial', sans-serif;
		}

		body
		{
			font-family: 'Helvetica','Arial', sans-serif;
		}

        #chat-items ul
		{
 			background-color: white;
    		max-height: 120px;/*The important part*/
    		overflow: scroll;
    		-webkit-overflow-scrolling: touch;
 		}

        #chat-items li
		{
			list-style-type: none;
    	}

        .table
        {
            color: #F9F8F8;

        }

        .table td
        {
            color: #1a2a67;
            vertical-align: middle;
        }

        .table-striped > tbody > tr:nth-child(2n+1) > td, .table-striped > tbody > tr:nth-child(2n+1) > th
        {
            background-color: #42A1C9;
        }

        .table-striped > tbody > tr:nth-child(2n) > td, .table-striped > tbody > tr:nth-child(2n) > th
        {
            background-color: #1a2a67;
        }

        .table a
        {
            color: #1a2a67;
        }

        .asteriskField
        {
            display: none;
        }

        .requiredField
        {
            display: none;
        }

        .thumbnail
        {
            padding-bottom: 30px;
        }

        .card-img
        {
            width: 350px;
            height: 250px;
        }

        .caption h3
        {
            padding-top: 10px;
        }

        .caption p
        {
            text-align: left;
            padding-left: 25px;
        }

	</style>

    <script>

        $(function()
        {
            $("#id_date").datetimepicker();
            format: 'YYYY-MM-DD HH:MM'
        });

    </script>
</head>

<body style="background-color: #42A1C9;">

<!--Navbar Starts Here -->
	<nav class="mb-1 navbar navbar-expand-lg navbar-dark secondary-color lighten-1">
        <a class="navbar-brand" href="{% url 'index' %}">Help Without Judgment</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555" aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
            <ul class="navbar-nav mr-auto" style="font-size: larger;">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                {% if user.profile.is_organization == False %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_request' %}">Create Request</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'open_requests' %}">Available Requests</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'past_requests' %}">Past Requests</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'inbox' %}">View Inbox</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'non_profits' %}">Local Non-Profits</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'support' %}">Support</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto nav-flex-icons">
                <li class="nav-item avatar dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-55" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="{{ user.profile.image.url }}" class="rounded-circle z-depth-0" alt="avatar image" width="100px" height="100px">
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg-right dropdown-secondary" aria-labelledby="navbarDropdownMenuLink-55">
                        <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <!--/.Navbar -->

	<!-- Dashboard (jumbotron) Begins -->
	<div style="background-color: #F9F8F8;" class="jumbotron d-flex align-items center min-vh-100" id="dashboard_greeting">
    	<!-- Dashboard greeting container Begins -->
		<div class="container text-center" id="jumbotron_text_container">
			<h1 class="display-4" align="center">{% block pageheader %}Dashboard{% endblock %}</h1>

            {% block greeting %}
            {% endblock greeting%}
            <hr class="my-4">

            {% block script %}
            {% endblock script%}

            {% block content %}
            {% endblock content%}

            {% block results %}
            {% endblock results %}

        </div><!-- End container -->
    </div> <!-- End jumbotron -->

    <!-- Footer Begins Here-->
    <footer class="page-footer font-small teal pt-4">

      <!-- Container Starts Here-->
      <div class="container-fluid text-center text-md-left">

        <!-- Grid Row Starts Here-->
        <div class="row">

          <!-- Grid Column Starts Here-->
          <div class="col-md-6 mt-md-0 mt-3">

            <!-- Content -->
            <h5 class="text-uppercase font-weight-bold">About</h5>
            <p>Help Without Judgment was conceived to make two things easier: providing direct help to local
                communities and receiving help without giving up your privacy. In this age of technology and
                connectivity, we hope you will find it in your heart to make a difference in the life
                of someone in your community.</p>

          </div> <!-- End of Grid Column -->

          <hr class="clearfix w-100 d-md-none pb-3">

          <!-- Grid Column Starts Here-->
          <div class="col-md-6 mb-md-0 mb-3">

            <!-- Content -->
            <h5 class="text-uppercase font-weight-bold">Advice</h5>
            <p>Although we are delighted that you are choosing to participate in this project, we want to remind you to
               never put yourself in a situation that makes you uncomfortable, and to meet in public places when possible.
               Your personal safety, the safety of your family, or anyone you care about is not worth being at risk. When
               in doubt, err on the side of caution or meet outside of a local police department to ensure your safety.</p>
          </div> <!-- End of Grid Column -->
        </div> <!-- End of Grid Row -->
      </div> <!-- End of Container -->

      <!-- Copyright Starts Here-->
      <div class="footer-copyright text-center py-3">© 2019 Copyright:
        <a href="{% url 'index' %}" style="color: #F9F8F8;"> Help Without Judgment </a>
      </div> <!-- End of Copyright -->

    </footer> <!-- End of Footer -->
</body>
</html>

user/templates/user/create_request.html
{% extends "user/base.html" %}
{% load crispy_forms_tags %}

{% block pageheader %}Create a New Request{% endblock %}

{% block content %}
    {% if user.profile.is_organization == True %}
    <h2>Organizations are not able to create service requests!</h2>
    {% else %}
    <div class="container">
        <form action= "{% url 'create_request' %}" method="POST" class="col-md-4 offset-4">

            {% csrf_token %}

            <div class="form-group">
                {{ form.type|as_crispy_field }}
            </div>

            <div class="form-group">
                {{ form.description|as_crispy_field }}
            </div>

            <button type="submit" class="btn btn-link" style="background: #1a2a67; color: #F9F8F8;"><i class="fas fa-plus-square"></i> Create Request</button>
        </form>
    </div>
    {% endif %}

{% endblock content %}

user/templates/user/inbox.html
{% extends "user/base.html" %}

{% block pageheader %}
    {% if user.profile.is_moderator == False %}
        Inbox
    {% else %}
        Moderator Inbox
    {% endif %}
{% endblock pageheader %}

{% block content %}
{% if user.profile.is_moderator == False %}
    {% if messages.count > 0 %}
        <h4> These are your current conversations </h4>
        <hr class="my-4">
        <!-- Table Starts Here -->
        <table class="table table-bordered table-hover">
            <thead>
            <tr style="background-color: #1a2a67;">
                <th style="width: 20%" scope="col"><h4>Profile Image</h4></th>
                <th style="width: 30%" scope="col"><h4>Username</h4></th>
                <th style="width: 25%" scope="col"><h4>Date Began</h4></th>
                <th style="width: 25%" scope="col"><h4>Last Message</h4></th>
                <!-- <th style="width: 20%" scope="col"><h4>Message</h4></th> -->
                <!--<th style="width: 20%" scope="col"><h4>Website</h4></th>-->
            </tr>
            </thead>
            {% for message in messages %}
                {% if message.first == user %}
                    <tr style="vertical-align: middle;">
                    <th scope="row"><a href="/messages/{{ message.second.username }}"><img src="{{ message.second.profile.image.url }}" class="rounded-circle z-depth-0" alt="avatar image" width="100px" height="100px"> </a></th>
                        <td><a href="/messages/{{ message.second.username }}"><h5>{{ message.second.username }}</h5></a></td>
                        <td><a href="/messages/{{ message.second.username }}"><h5>{{ message.timestamp }}</h5></a></td>
                        <!--<td><a href="/messages/{{ message.second.username }}"><h5>{{ message.updated }}</h5></a></td> -->
                        <td><a href="/messages/{{ message.second.username }}"><h5> {{ message.chatmessage_set.last.timestamp }}  </h5></a></td>
                    </tr>
                {% else %}
                    <tr>
                    <th scope="row"><a href="/messages/{{ message.first.username }}"><img src="{{ message.first.profile.image.url }}" class="rounded-circle z-depth-0" alt="avatar image" width="100px" height="100px"> </a></th>
                        <td><a href="/messages/{{ message.first.username }}"><h5>{{ message.first.username }}</h5></a></td>
                        <td><a href="/messages/{{ message.first.username }}"><h5>{{ message.timestamp }}</h5></a></td>
                        <!--<td><a href="/messages/{{ message.first.username }}"><h5>{{ message.updated }}</h5></a></td>-->
                        <td><a href="/messages/{{ message.first.username }}"><h5> {{ message.chatmessage_set.last.timestamp }}  </h5></a></td>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>
        <!-- Table Ends Here -->

    {% else %}
        <h4> You do not currently have any conversations in your Inbox.</h4>
    {% endif %}

{% else %}
    {% if messages.count > 0 %}
        <h4> These are all user conversations </h4>
        <hr class="my-4">
        <div class="row">
        {% for message in messages %}
            <div class="col-sm-4 col-md-r">
                <div class="card" style="width: 18rem;">
                    <a id="message_url" href="/messages/{{ message.second.username }}"><img src="{{ message.second.profile.image.url }}" class="card-img-top" width="300px" height="250px" alt="profile_image"></a>
                    <div class="card-body">
                        <p class="card-text">Conversation between {{ message.first }} & {{ message.second }}</p>
                        <p class="card-text">Last Message: {{ message.updated }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h4>There are not currently any user conversations.</h4>
    {% endif %}
{% endif %}
{% endblock content %}

user/templates/user/non_profits.html
{% extends "user/base.html" %}

{% block pageheader %}Local Non-Profit Organizations{% endblock pageheader %}

{% block content %}
    <h4>There are local resources that can provide different, and sometimes more long-term assistance.</h4>
    <hr class="my-4">
    <form action="{% url 'non_profits' %}" method="POST" class="empty-form">
        {% csrf_token %}
        <div class="form-group" align="center">
            <div class="col-sm-3 col-md-r">
                <div class="form-group" align="center">
                    <label for="city_lookup">Enter a city</label>
                    <input style="text-align:center;" name="city_input" type="text" id="city_input" class="form-control">
                    <label for="state_lookup"><br>Enter the state initials</label>
                    <input style="text-align:center;" name="state_input" type="text" id="state_input" class="form-control"><br>
                </div>
                <br><button type="submit" value="" name="submit" class="btn btn-link" style="background: #1a2a67; color: #F9F8F8;">Lookup Resources</button>
            </div>
        </div>
    </form>
{% endblock content %}

{% block results%}
    {% if charities %}
        <hr class="my-4">
        <table class="table table-bordered table-hover">
            <thead>
                <tr style="background-color: #42A1C9;">
                    <th colspan="4"><h3>Local Non-Profit Search Results</h3></th>
                </tr>
                <tr style="background-color: #1a2a67;">
                    <th style="width: 30%" scope="col"><h4>Name</h4></th>
                    <th style="width: 25%" scope="col"><h4>Address</h4></th>
                    <th style="width: 25%" scope="col"><h4>City</h4></th>
                    <th style="width: 20%" scope="col"><h4>Zip Code</h4></th>
                    <!--<th style="width: 20%" scope="col"><h4>Website</h4></th>-->
                </tr>
            </thead>

            {% for item in charities.items %}
                <tr>
                    <th scope="row"><a href={{ item.1.href_string }} target="_blank"><h5>{{ item.1.name }}</h5></a></th>
                    <td><h5>{{ item.1.address }}</h5></td>
                    <td><h5>{{ item.1.city }}</h5></td>
                    <td><h5>{{ item.1.zipcode }}</h5></td>
                    <!--<td><h5>{{ item.1.website }}</h5></td>-->
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock results%}

user/templates/user/open_requests.html
{% extends "user/base.html" %}

{% block pageheader %}View Available Requests{% endblock %}

{% block content %}
    {% if user.profile.is_organization == True and user.profile.is_verified == False %}
    <h3> You cannot view/accept requests until your organization account is verified!</h3>
    {% else %}
    <div class="row">
        {% for request in requests %}
            <div class="col-sm-4 col-md-r">
                <div class="thumbnail">
                    {% if request.type == 'Furniture Service' %}
                    <img style="border: 2px solid black;" class="card-img" src="../static/registration/images/furniture_request_default_image.jpg" alt="furniture_request_default_image.jpg">
                    {% elif request.type == 'Food Service' %}
                    <img style="border: 2px solid black;" class="card-img" src="../static/registration/images/food_request_default_image.jpg" alt="food_request_default_image.jpg">
                    {% elif request.type == 'Clothing Service' %}
                    <img style="border: 2px solid black;" class="card-img" src="../static/registration/images/clothing_request_default_image.jpg" alt="clothing_request_default_image.jpg">
                    {% elif request.type == 'Interpreter Service' %}
                    <img style="border: 2px solid black;" class="card-img" src="../static/registration/images/interpreter_request_default_image.png" alt="interpreter_request_default_image.jpg">
                    {% elif request.type == 'Transportation Service' %}
                    <img style="border: 2px solid black;" class="card-img" src="../static/registration/images/transportation_request_default_image.jpg" alt="transportation_request_default_image.jpg">
                    {% endif %}
                    <div class="caption">
                        <h3><strong>Status: </strong>{{ request.status }}</h3>
                        <p><strong>Type: </strong>{{ request.type }}</p>
                        <p><strong>Requested By: </strong>{{ request.requester }}</p>
                        <p><strong>Description: </strong>{{ request.description }}</p>
                        <p><strong>Created On: </strong>{{ request.date_created|date:"F d, Y" }}</p>
                        {% if request.date_appointment != null and request.appointment_confirmed == False %}
                            <p><strong>Request Appointment: You have a pending schedule appointment.</strong></p>
                        {% elif request.date_appointment != null and request.appointment_confirmed == True %}
                            <p><strong>Request Appointment: </strong>{{ request.date_appointment }}</p>
                        {% endif %}
                        <p><strong>Completed On: </strong>{{ request.date_completed }}</p>
                        <div class="empty-form">
                            <form action= "{% url 'open_requests' %}" method="POST" class="form">
                                {% csrf_token %}
                                <input type="hidden" name="primary_key" value="{{ request.pk }}">
                                <button type="submit" class="btn btn-link" style="background: #48ad76; color: #F9F8F8;"><i class="fas fa-check-square"></i> Accept</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    {% endif %}
{% endblock content %}